### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by schronck** [agoraxyz/telegram-runner#247]
## Problem

There are some functions where we use the wrong logging level (`verbose` instead of `error`).
The logs can be unnecessarily long, so we should print only the message from the error object.
Sometimes it would be useful to have extra metadata in error logs, such as group ID or user ID to know in which group the error occured.

## Tasks

- [x] change `verbose` to `error`
- [x] trim errors for logging
- [x] add additional info for errors
